### ISSUE TITLE
Minimalistic version without Forcespro

### ISSUE THREAD

**Issue by saxenam06** [XuShenLZ/dataMPC_parking#1]
Hello, Could you please suggest how I may convert the Online_MPC version of the codes and successfully run the strategy guided OBCA without using Forces pro as it's not open source. Many Thanks anyways for a great repository and open sourcing the codes.

**Comment by XuShenLZ** [comment]
Hi thanks for your interest in this project!

Yeah in the final folder cleanup, we only keep the scripts with Forces Pro implementation in the main folders for easy access. But there are CasAdi implementation in the "BACKUP" folders.

My rough suggestions would be:
1. Move the `online_HOBCA_strat_casadi.m` from the `experiments/backup` folder to `experiments`
2. Bring the `hpp_obca_controller_casadi.m` from the `controllers/backup` folder to `controllers`
3. Then you should be able to run `online_HOBCA_strat_casadi.m` after changing the `exp_num` to let it load the downloaded demo file.

**Comment by saxenam06** [comment]
HI, Thanks for the quick response. Yes the CasAdi implementation is working as you explained. Thank you!

**Comment by XuShenLZ** [comment]
Glad it works. I am not sure about the performance since we might have changed the tuning after using Forces.

**Comment by saxenam06** [comment]
Thanks for your remark. Yes, it's chosing emergency braking as the preferred policy, letting the TV pass and then starting again towards goal. I am looking deeper into the codes step by step.
