### ISSUE TITLE
Extract more TV trajectories using extract_trajs.ipynb

### ISSUE THREAD

**Issue by saxenam06** [XuShenLZ/dataMPC_parking#2]
Hello, I would like to extract more TV trajectories for more thorough analysis of the performance of Nominal MPC & the Strategy learning modules. 
Tried extract_trajs.ipynb but unable to find .pkl files and also the bags folder in the path ../../carla/PythonAPI/examples/
Could you please help so that I can have or fetch more TV trajectories.

**Comment by XuShenLZ** [comment]
Hi the TV trajectories are extracted from the [ParkPredict ](bit.ly/parkpredict) dataset. Please submit a request there. The dataset will be in `.tfrecord` format and you may need to spend a little bit more effort than `extract_trajs.ipynb` to extract them into `.mat`. Sorry for the inconvenience.

**Comment by saxenam06** [comment]
Hi, Yes I recieved the .tfrecord files from the ParkPredict dataset. However, as I can see .tfrecord files consist of various features and labels of each demonstration and as you said some work is required to recombine them to get back the entire demonstration. I recognized that the .pkl files consist of the entire demonstration as required by the nominal mpc for solving first the optimal control problem. Would it be possible for you to please share the .pkl files to get started directly?

**Comment by XuShenLZ** [comment]
I see your point. Yes .tfrecord files are initially processed for machine learning purposes. We are currently combining some new raw data with the previous pkl files so that we can publish them as a new parking dataset with much richer scenarios (with full trajectories for generic self-driving / traffic) purposes. I will let you know when that becomes available.

**Comment by saxenam06** [comment]
Oh that sounds great! Sure, please let me know.
